# name: open-telemetry-model

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib-dev
    ports:
      - "4318:4318"
      - "4317:4317"
      - "8889:8889"
    volumes:
      - type: bind 
        source: ./OtelCollector/collector-config.yaml
        target: /etc/otel/config.yaml

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./Prometheus/Database
        target: /etc/prometheus/data
      - type: bind
        source: ./Prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
      - "9096:9096"
    volumes:
      - type: bind
        source: ./Loki/loki-config.yaml
        target: /etc/loki/loki-config.yaml

  promtail:
    image: grafana/promtail
    volumes:
      - type: bind
        source: ./Loki/promtail-config.yaml
        target: /etc/promtail/promtail-config.yaml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  tempo:
    image: grafana/tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - type: bind
        source: ./Tempo/tempo.yaml
        target: /etc/tempo.yaml
    ports:
      - "3200:3200"   # tempo